// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {employees} from '../models';

export function CreateEmployee(arg1:handlers.CreateEmployeeRequest):Promise<employees.Employee>;

export function DeleteEmployee(arg1:handlers.DeleteEmployeeRequest):Promise<void>;

export function GetEmployee(arg1:handlers.GetEmployeeRequest):Promise<employees.Employee>;

export function GetMe(arg1:string):Promise<handlers.GetMeResponse>;

export function ListEmployees(arg1:handlers.ListEmployeesRequest):Promise<handlers.EmployeeListResponse>;

export function Login(arg1:handlers.LoginRequest):Promise<handlers.LoginResponse>;

export function Logout(arg1:handlers.LogoutRequest):Promise<void>;

export function UpdateEmployee(arg1:handlers.UpdateEmployeeRequest):Promise<employees.Employee>;
