// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLeave(arg1) {
  return window['go']['main']['App']['ApplyLeave'](arg1);
}

export function ApproveLeave(arg1) {
  return window['go']['main']['App']['ApproveLeave'](arg1);
}

export function ApprovePayrollBatch(arg1) {
  return window['go']['main']['App']['ApprovePayrollBatch'](arg1);
}

export function CancelLeave(arg1) {
  return window['go']['main']['App']['CancelLeave'](arg1);
}

export function CreateDepartment(arg1) {
  return window['go']['main']['App']['CreateDepartment'](arg1);
}

export function CreateEmployee(arg1) {
  return window['go']['main']['App']['CreateEmployee'](arg1);
}

export function CreateLeaveType(arg1) {
  return window['go']['main']['App']['CreateLeaveType'](arg1);
}

export function CreatePayrollBatch(arg1) {
  return window['go']['main']['App']['CreatePayrollBatch'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteDepartment(arg1) {
  return window['go']['main']['App']['DeleteDepartment'](arg1);
}

export function DeleteEmployee(arg1) {
  return window['go']['main']['App']['DeleteEmployee'](arg1);
}

export function ExportAttendanceSummaryReportCSV(arg1) {
  return window['go']['main']['App']['ExportAttendanceSummaryReportCSV'](arg1);
}

export function ExportAuditLogReportCSV(arg1) {
  return window['go']['main']['App']['ExportAuditLogReportCSV'](arg1);
}

export function ExportEmployeeReportCSV(arg1) {
  return window['go']['main']['App']['ExportEmployeeReportCSV'](arg1);
}

export function ExportLeaveRequestsReportCSV(arg1) {
  return window['go']['main']['App']['ExportLeaveRequestsReportCSV'](arg1);
}

export function ExportPayrollBatchCSV(arg1) {
  return window['go']['main']['App']['ExportPayrollBatchCSV'](arg1);
}

export function ExportPayrollBatchesReportCSV(arg1) {
  return window['go']['main']['App']['ExportPayrollBatchesReportCSV'](arg1);
}

export function GeneratePayrollEntries(arg1) {
  return window['go']['main']['App']['GeneratePayrollEntries'](arg1);
}

export function GetCompanyLogo(arg1) {
  return window['go']['main']['App']['GetCompanyLogo'](arg1);
}

export function GetDashboardSummary(arg1) {
  return window['go']['main']['App']['GetDashboardSummary'](arg1);
}

export function GetDepartment(arg1) {
  return window['go']['main']['App']['GetDepartment'](arg1);
}

export function GetEmployee(arg1) {
  return window['go']['main']['App']['GetEmployee'](arg1);
}

export function GetLeaveBalance(arg1) {
  return window['go']['main']['App']['GetLeaveBalance'](arg1);
}

export function GetLunchSummary(arg1) {
  return window['go']['main']['App']['GetLunchSummary'](arg1);
}

export function GetMe(arg1) {
  return window['go']['main']['App']['GetMe'](arg1);
}

export function GetMyAttendanceRange(arg1) {
  return window['go']['main']['App']['GetMyAttendanceRange'](arg1);
}

export function GetMyLeaveBalance(arg1) {
  return window['go']['main']['App']['GetMyLeaveBalance'](arg1);
}

export function GetPayrollBatch(arg1) {
  return window['go']['main']['App']['GetPayrollBatch'](arg1);
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function GetStartupHealth() {
  return window['go']['main']['App']['GetStartupHealth']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function ListAllLeaveRequests(arg1) {
  return window['go']['main']['App']['ListAllLeaveRequests'](arg1);
}

export function ListAttendanceByDate(arg1) {
  return window['go']['main']['App']['ListAttendanceByDate'](arg1);
}

export function ListAttendanceSummaryReport(arg1) {
  return window['go']['main']['App']['ListAttendanceSummaryReport'](arg1);
}

export function ListAuditLogReport(arg1) {
  return window['go']['main']['App']['ListAuditLogReport'](arg1);
}

export function ListAuditLogs(arg1) {
  return window['go']['main']['App']['ListAuditLogs'](arg1);
}

export function ListDepartments(arg1) {
  return window['go']['main']['App']['ListDepartments'](arg1);
}

export function ListEmployeeReport(arg1) {
  return window['go']['main']['App']['ListEmployeeReport'](arg1);
}

export function ListEmployees(arg1) {
  return window['go']['main']['App']['ListEmployees'](arg1);
}

export function ListLeaveRequestsReport(arg1) {
  return window['go']['main']['App']['ListLeaveRequestsReport'](arg1);
}

export function ListLeaveTypes(arg1) {
  return window['go']['main']['App']['ListLeaveTypes'](arg1);
}

export function ListLockedDates(arg1) {
  return window['go']['main']['App']['ListLockedDates'](arg1);
}

export function ListMyLeaveRequests(arg1) {
  return window['go']['main']['App']['ListMyLeaveRequests'](arg1);
}

export function ListPayrollBatches(arg1) {
  return window['go']['main']['App']['ListPayrollBatches'](arg1);
}

export function ListPayrollBatchesReport(arg1) {
  return window['go']['main']['App']['ListPayrollBatchesReport'](arg1);
}

export function ListUsers(arg1) {
  return window['go']['main']['App']['ListUsers'](arg1);
}

export function LockDate(arg1) {
  return window['go']['main']['App']['LockDate'](arg1);
}

export function LockPayrollBatch(arg1) {
  return window['go']['main']['App']['LockPayrollBatch'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function PostAbsentToLeave(arg1) {
  return window['go']['main']['App']['PostAbsentToLeave'](arg1);
}

export function Refresh(arg1) {
  return window['go']['main']['App']['Refresh'](arg1);
}

export function RejectLeave(arg1) {
  return window['go']['main']['App']['RejectLeave'](arg1);
}

export function ReloadConfigAndReconnect() {
  return window['go']['main']['App']['ReloadConfigAndReconnect']();
}

export function ResetUserPassword(arg1) {
  return window['go']['main']['App']['ResetUserPassword'](arg1);
}

export function SaveDatabaseConfig(arg1) {
  return window['go']['main']['App']['SaveDatabaseConfig'](arg1);
}

export function SaveFileWithDialog(arg1) {
  return window['go']['main']['App']['SaveFileWithDialog'](arg1);
}

export function SetLeaveTypeActive(arg1) {
  return window['go']['main']['App']['SetLeaveTypeActive'](arg1);
}

export function SetUserActive(arg1) {
  return window['go']['main']['App']['SetUserActive'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1);
}

export function UnlockDate(arg1) {
  return window['go']['main']['App']['UnlockDate'](arg1);
}

export function UpdateDepartment(arg1) {
  return window['go']['main']['App']['UpdateDepartment'](arg1);
}

export function UpdateEmployee(arg1) {
  return window['go']['main']['App']['UpdateEmployee'](arg1);
}

export function UpdateLeaveType(arg1) {
  return window['go']['main']['App']['UpdateLeaveType'](arg1);
}

export function UpdatePayrollEntryAmounts(arg1) {
  return window['go']['main']['App']['UpdatePayrollEntryAmounts'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}

export function UploadCompanyLogo(arg1) {
  return window['go']['main']['App']['UploadCompanyLogo'](arg1);
}

export function UpsertAttendance(arg1) {
  return window['go']['main']['App']['UpsertAttendance'](arg1);
}

export function UpsertEntitlement(arg1) {
  return window['go']['main']['App']['UpsertEntitlement'](arg1);
}

export function UpsertLunchVisitors(arg1) {
  return window['go']['main']['App']['UpsertLunchVisitors'](arg1);
}
