// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {leave} from '../models';
import {payroll} from '../models';
import {departments} from '../models';
import {employees} from '../models';
import {users} from '../models';

export function ApplyLeave(arg1:handlers.ApplyLeaveRequest):Promise<leave.LeaveRequest>;

export function ApproveLeave(arg1:handlers.LeaveActionRequest):Promise<leave.LeaveRequest>;

export function ApprovePayrollBatch(arg1:handlers.PayrollBatchActionRequest):Promise<payroll.PayrollBatch>;

export function CancelLeave(arg1:handlers.LeaveActionRequest):Promise<leave.LeaveRequest>;

export function CreateDepartment(arg1:handlers.CreateDepartmentRequest):Promise<departments.Department>;

export function CreateEmployee(arg1:handlers.CreateEmployeeRequest):Promise<employees.Employee>;

export function CreateLeaveType(arg1:handlers.CreateLeaveTypeRequest):Promise<leave.LeaveType>;

export function CreatePayrollBatch(arg1:handlers.CreatePayrollBatchRequest):Promise<payroll.PayrollBatch>;

export function CreateUser(arg1:handlers.CreateUserRequest):Promise<users.User>;

export function DeleteDepartment(arg1:handlers.DeleteDepartmentRequest):Promise<void>;

export function DeleteEmployee(arg1:handlers.DeleteEmployeeRequest):Promise<void>;

export function ExportPayrollBatchCSV(arg1:handlers.PayrollBatchActionRequest):Promise<string>;

export function GeneratePayrollEntries(arg1:handlers.PayrollBatchActionRequest):Promise<void>;

export function GetDepartment(arg1:handlers.GetDepartmentRequest):Promise<departments.Department>;

export function GetEmployee(arg1:handlers.GetEmployeeRequest):Promise<employees.Employee>;

export function GetLeaveBalance(arg1:handlers.LeaveBalanceRequest):Promise<leave.LeaveBalance>;

export function GetMe(arg1:string):Promise<handlers.GetMeResponse>;

export function GetMyLeaveBalance(arg1:handlers.LeaveBalanceRequest):Promise<leave.LeaveBalance>;

export function GetPayrollBatch(arg1:handlers.GetPayrollBatchRequest):Promise<payroll.PayrollBatchDetail>;

export function GetUser(arg1:handlers.GetUserRequest):Promise<users.User>;

export function ListAllLeaveRequests(arg1:handlers.ListLeaveRequestsRequest):Promise<Array<leave.LeaveRequest>>;

export function ListDepartments(arg1:handlers.ListDepartmentsRequest):Promise<handlers.DepartmentListResponse>;

export function ListEmployees(arg1:handlers.ListEmployeesRequest):Promise<handlers.EmployeeListResponse>;

export function ListLeaveTypes(arg1:handlers.ListLeaveTypesRequest):Promise<Array<leave.LeaveType>>;

export function ListLockedDates(arg1:handlers.ListLockedDatesRequest):Promise<Array<leave.LeaveLockedDate>>;

export function ListMyLeaveRequests(arg1:handlers.ListLeaveRequestsRequest):Promise<Array<leave.LeaveRequest>>;

export function ListPayrollBatches(arg1:handlers.ListPayrollBatchesRequest):Promise<payroll.ListBatchesResult>;

export function ListUsers(arg1:handlers.ListUsersRequest):Promise<users.ListUsersResult>;

export function LockDate(arg1:handlers.LockDateRequest):Promise<leave.LeaveLockedDate>;

export function LockPayrollBatch(arg1:handlers.PayrollBatchActionRequest):Promise<payroll.PayrollBatch>;

export function Login(arg1:handlers.LoginRequest):Promise<handlers.LoginResponse>;

export function Logout(arg1:handlers.LogoutRequest):Promise<void>;

export function RejectLeave(arg1:handlers.RejectLeaveRequest):Promise<leave.LeaveRequest>;

export function ResetUserPassword(arg1:handlers.ResetUserPasswordRequest):Promise<void>;

export function SetLeaveTypeActive(arg1:handlers.SetLeaveTypeActiveRequest):Promise<leave.LeaveType>;

export function SetUserActive(arg1:handlers.SetUserActiveRequest):Promise<users.User>;

export function UnlockDate(arg1:handlers.UnlockDateRequest):Promise<void>;

export function UpdateDepartment(arg1:handlers.UpdateDepartmentRequest):Promise<departments.Department>;

export function UpdateEmployee(arg1:handlers.UpdateEmployeeRequest):Promise<employees.Employee>;

export function UpdateLeaveType(arg1:handlers.UpdateLeaveTypeRequest):Promise<leave.LeaveType>;

export function UpdatePayrollEntryAmounts(arg1:handlers.UpdatePayrollEntryAmountsRequest):Promise<payroll.PayrollEntry>;

export function UpdateUser(arg1:handlers.UpdateUserRequest):Promise<users.User>;

export function UpsertEntitlement(arg1:handlers.UpsertEntitlementRequest):Promise<leave.LeaveEntitlement>;
