// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLeave(arg1) {
  return window['go']['main']['App']['ApplyLeave'](arg1);
}

export function ApproveLeave(arg1) {
  return window['go']['main']['App']['ApproveLeave'](arg1);
}

export function CancelLeave(arg1) {
  return window['go']['main']['App']['CancelLeave'](arg1);
}

export function CreateDepartment(arg1) {
  return window['go']['main']['App']['CreateDepartment'](arg1);
}

export function CreateEmployee(arg1) {
  return window['go']['main']['App']['CreateEmployee'](arg1);
}

export function CreateLeaveType(arg1) {
  return window['go']['main']['App']['CreateLeaveType'](arg1);
}

export function DeleteDepartment(arg1) {
  return window['go']['main']['App']['DeleteDepartment'](arg1);
}

export function DeleteEmployee(arg1) {
  return window['go']['main']['App']['DeleteEmployee'](arg1);
}

export function GetDepartment(arg1) {
  return window['go']['main']['App']['GetDepartment'](arg1);
}

export function GetEmployee(arg1) {
  return window['go']['main']['App']['GetEmployee'](arg1);
}

export function GetLeaveBalance(arg1) {
  return window['go']['main']['App']['GetLeaveBalance'](arg1);
}

export function GetMe(arg1) {
  return window['go']['main']['App']['GetMe'](arg1);
}

export function GetMyLeaveBalance(arg1) {
  return window['go']['main']['App']['GetMyLeaveBalance'](arg1);
}

export function ListAllLeaveRequests(arg1) {
  return window['go']['main']['App']['ListAllLeaveRequests'](arg1);
}

export function ListDepartments(arg1) {
  return window['go']['main']['App']['ListDepartments'](arg1);
}

export function ListEmployees(arg1) {
  return window['go']['main']['App']['ListEmployees'](arg1);
}

export function ListLeaveTypes(arg1) {
  return window['go']['main']['App']['ListLeaveTypes'](arg1);
}

export function ListLockedDates(arg1) {
  return window['go']['main']['App']['ListLockedDates'](arg1);
}

export function ListMyLeaveRequests(arg1) {
  return window['go']['main']['App']['ListMyLeaveRequests'](arg1);
}

export function LockDate(arg1) {
  return window['go']['main']['App']['LockDate'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function RejectLeave(arg1) {
  return window['go']['main']['App']['RejectLeave'](arg1);
}

export function SetLeaveTypeActive(arg1) {
  return window['go']['main']['App']['SetLeaveTypeActive'](arg1);
}

export function UnlockDate(arg1) {
  return window['go']['main']['App']['UnlockDate'](arg1);
}

export function UpdateDepartment(arg1) {
  return window['go']['main']['App']['UpdateDepartment'](arg1);
}

export function UpdateEmployee(arg1) {
  return window['go']['main']['App']['UpdateEmployee'](arg1);
}

export function UpdateLeaveType(arg1) {
  return window['go']['main']['App']['UpdateLeaveType'](arg1);
}

export function UpsertEntitlement(arg1) {
  return window['go']['main']['App']['UpsertEntitlement'](arg1);
}
