// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEmployee(arg1) {
  return window['go']['main']['App']['CreateEmployee'](arg1);
}

export function DeleteEmployee(arg1) {
  return window['go']['main']['App']['DeleteEmployee'](arg1);
}

export function GetEmployee(arg1) {
  return window['go']['main']['App']['GetEmployee'](arg1);
}

export function GetMe(arg1) {
  return window['go']['main']['App']['GetMe'](arg1);
}

export function ListEmployees(arg1) {
  return window['go']['main']['App']['ListEmployees'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function UpdateEmployee(arg1) {
  return window['go']['main']['App']['UpdateEmployee'](arg1);
}
