// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function GetMe(arg1:string):Promise<handlers.GetMeResponse>;

export function Login(arg1:handlers.LoginRequest):Promise<handlers.LoginResponse>;

export function Logout(arg1:handlers.LogoutRequest):Promise<void>;
